/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import java.sql.SQLException;
import java.time.LocalDate;
import java.util.List;

import javax.swing.JButton;
import javax.swing.JOptionPane;

import Controladores.ControladorVentanaCompraBoletas;
import DTOs.CompraDTO;
import DTOs.FuncionDTO;
import DTOs.PeliculaDTO;
import DTOs.SalaDTO;
import DTOs.UsuarioDTO;
import Exceptions.PeliculaNoEncontradaException;
import Exceptions.UsuarioNoEncontradoException;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author servi
 */
public class CompraBoletas extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form CompraBoletas
     */
    
    UsuarioDTO usuario;
    ControladorVentanaCompraBoletas controladorVentanaCompraBoletas;
    
    public CompraBoletas(UsuarioDTO usuario) {
        initComponents();
        
        setLocationRelativeTo(this);
        this.usuario = usuario;
        this.controladorVentanaCompraBoletas = new ControladorVentanaCompraBoletas();
        
        llenarCbPeliculas();
        llenaCbFunciones(null);
        
    }

    
    public void llenarCbPeliculas() {
    	try {
    		List<PeliculaDTO> peliculasDisponibles = controladorVentanaCompraBoletas.obtenerPeliculasConFunciones();
    		cbPeliculas.removeAllItems();
    		cbPeliculas.addItem("--Seleccione una pelicula--");
            for (int i = 0; i < peliculasDisponibles.size(); i++) {
            	PeliculaDTO pelicula = peliculasDisponibles.get(i);
                cbPeliculas.addItem(pelicula);
            }
    	}catch(SQLException | PeliculaNoEncontradaException e) {
    		e.printStackTrace();
    	}
    }
    
    public void llenaCbFunciones(PeliculaDTO pelicula) {
    	if(pelicula != null) {
    		try {
        		List<FuncionDTO> funcionesPorPelicula = controladorVentanaCompraBoletas.obtenerFuncionesPorPelicula(pelicula.getId_pelicula());
        		cbFunciones.removeAllItems();
        		cbFunciones.addItem("--Seleccione una función--");
                for (int i = 0; i < funcionesPorPelicula.size(); i++) {
                	FuncionDTO funcion = funcionesPorPelicula.get(i);
                	cbFunciones.addItem(funcion);
                }
        	}catch(SQLException | PeliculaNoEncontradaException e) {
        		e.printStackTrace();
        	}
    	} else {
    		cbFunciones.removeAllItems();
    		cbFunciones.addItem("--Seleccione una función--");
    	}
    }
    
    private void cargarSala(SalaDTO sala){
    	borrarContenidoPanel();
    	
    	JButton[][] sillas = generarMatriz(sala.getCapacidad());
        int ancho = 50;
        int alto = 50;
        int separado = 20;
        int contador = 1;
        for(int i= 0; i < sillas.length; i++){
            for(int j = 0; j < sillas[i].length; j++){
                //setBounds(posX, posY, ancho, alto)
                sillas[i][j] = new JButton();
                sillas[i][j].setBounds(
                        (j * ancho + separado),//posX
                        (i * alto + separado),//posY
                        ancho, alto);
                sillas[i][j].addActionListener(this); //Cada que se de click se lanza el evento y será resuelto por la ventana
                sillas[i][j].setText(contador + "");
                panelMatrizSillas.add(sillas[i][j]); 
                contador++;
            }
        }
    }
    
    private JButton[][] generarMatriz(int cantidadSillas){
    	int columnas = 8;
		int filas = cantidadSillas / columnas;
        JButton[][] matriz;

        if (cantidadSillas % columnas != 0) {
            matriz = new JButton[filas + 1][];

            for (int i = 0; i < filas; i++) {
                matriz[i] = new JButton[columnas];
            }
            int puestosFaltantes = cantidadSillas % columnas;
            matriz[matriz.length - 1] = new JButton[puestosFaltantes];
        } else {
            matriz = new JButton[filas][columnas];
        }
        return matriz;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelMatrizSillas = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbPeliculas = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbFunciones = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        sCantidad = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        labelSala = new javax.swing.JLabel();
        btnComprar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMatrizSillas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "SillasDisponibles", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        javax.swing.GroupLayout panelMatrizSillasLayout = new javax.swing.GroupLayout(panelMatrizSillas);
        panelMatrizSillas.setLayout(panelMatrizSillasLayout);
        panelMatrizSillasLayout.setHorizontalGroup(
            panelMatrizSillasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
        );
        panelMatrizSillasLayout.setVerticalGroup(
            panelMatrizSillasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Pelicula:");

        cbPeliculas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbPeliculas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbPeliculasItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Función:");

        cbFunciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbFunciones.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbFuncionesItemStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Cantidad:");

        sCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Correo:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Sala:");

        labelSala.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelSala.setText(" ");

        btnComprar.setText("Comprar");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(sCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(195, 195, 195))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbPeliculas, 0, 309, Short.MAX_VALUE)
                            .addComponent(txtCorreo)
                            .addComponent(labelSala, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbFunciones, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnComprar)
                .addGap(184, 184, 184))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbFunciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSala, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(sCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(btnComprar)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("COMPRA DE BOLETAS");

        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnCerrarSesion.setText("CERRAR SESIÓN");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelMatrizSillas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRegresar)
                        .addGap(294, 294, 294)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrarSesion)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 28, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegresar)
                            .addComponent(btnCerrarSesion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelMatrizSillas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        MenuInicioAdmin menuInicioAdmin = new MenuInicioAdmin(usuario);
        menuInicioAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        LoginUsuarios loginUsuarios = new LoginUsuarios();
        loginUsuarios.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        if(validarCampos()) {
        	try {
        		String correo = txtCorreo.getText();
        		
        		LocalDate fecha = LocalDate.now();
        		java.sql.Date sqlDate = java.sql.Date.valueOf(fecha);
        		
        		PeliculaDTO pelicula = (PeliculaDTO)cbPeliculas.getSelectedItem();
        		FuncionDTO funcion = (FuncionDTO)cbFunciones.getSelectedItem();
        		int cantidadBoletas = (int)sCantidad.getValue();
        		
        		Integer idUsuario = 0;
        		if(!correo.isEmpty()) {
        			UsuarioDTO cliente = controladorVentanaCompraBoletas.obtenerUsuarioPorCorreo(correo);
        			idUsuario = cliente.getId_usuario();
        		} else {
        			idUsuario = -1;
        	        int respuesta = JOptionPane.showConfirmDialog(null, "No ha proporcionado un correo. \nLe recordamos que el cliente no podrá acceder a los beneficios de los usuarios registrados o su historial\n y en caso de reclamo debe presentar la factura física. \n¿Desea continua?", "Confirmación", JOptionPane.YES_NO_OPTION);
        	        if (respuesta == JOptionPane.NO_OPTION) {
        	        	return;
        	        }
        		}
        		CompraDTO compra = new CompraDTO(0, sqlDate, idUsuario, cantidadBoletas);
        		controladorVentanaCompraBoletas.guardarCompra(compra);
        		limpiarCampos();
        		JOptionPane.showMessageDialog(null, "Compra registrada con éxito");
        	}catch (UsuarioNoEncontradoException ex) {
                JOptionPane.showMessageDialog(this, "Error al comprar boletas: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

			}
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, rellena todos los campos.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnComprarActionPerformed

    private void cbPeliculasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbPeliculasItemStateChanged
       if(cbPeliculas.getSelectedIndex() != 0){
           PeliculaDTO pelicula = (PeliculaDTO)cbPeliculas.getSelectedItem();
           llenaCbFunciones(pelicula);
           borrarContenidoPanel();
       } else {
    	   llenaCbFunciones(null);
       }
    }//GEN-LAST:event_cbPeliculasItemStateChanged

    private void cbFuncionesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbFuncionesItemStateChanged
    	if(cbFunciones.getSelectedIndex() != 0 && cbFunciones.getSelectedIndex() != -1){
            FuncionDTO funcion = (FuncionDTO)cbFunciones.getSelectedItem();
            SalaDTO sala = controladorVentanaCompraBoletas.buscarSala(funcion.getId_sala());
            labelSala.setText(sala.toString());
            cargarSala(sala);
        } else {
        	labelSala.setText("");
        }
    }//GEN-LAST:event_cbFuncionesItemStateChanged

    private void borrarContenidoPanel() {
    	panelMatrizSillas.removeAll();  // Elimina todos los componentes del panel
    	panelMatrizSillas.revalidate(); // Revalida el diseño del panel
    	panelMatrizSillas.repaint();    // Vuelve a pintar el panel
    }
    
    private boolean validarCampos() {
    	return !(cbFunciones.getSelectedIndex() == 0 || cbPeliculas.getSelectedIndex() == 0);
    }
    
    private void limpiarCampos() {
    	cbPeliculas.setSelectedIndex(0);
    	cbFunciones.setSelectedIndex(0);
    	sCantidad.setValue(1);
    	txtCorreo.setText("");
    	
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<Object> cbFunciones;
    private javax.swing.JComboBox<Object> cbPeliculas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelSala;
    private javax.swing.JPanel panelMatrizSillas;
    private javax.swing.JSpinner sCantidad;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables

    public void actionPerformed(ActionEvent e) {
    	System.out.println("Boton presionado");
    }
}
